### PR TITLE
Fix framework build for Xcode 10+

### PR DESCRIPTION
**Pull request by mustafardestroyer**
I was having issues building the framework on the latest version of
xcode. Specifically this error:

https://stackoverflow.com/questions/51153525/xcode-10-unable-to-attach-db-error

Following the advice the framework is able to successfully build.

### CODE REVIEW

**Comment by mustafardestroyer** [comment]
@louisjrpark @NeolabConvergence any interest in merging this PR? Is this repo still supported?

**Comment by Jin-neo** [comment]
Hello 

In my case when I first joined this project, I built it normally using XCode11.

I wonder If this problem still occurs when you use XCode11.

**Comment by mustafardestroyer** [comment]
@Jin-neo Thanks for the reply. 

To be clear this issue occurred for me using Version 11.5.

I should also clarify that this issue only occurs when you attempt to build the Framework aggregate target, the library target works fine.

Are you able to successfully build the framework aggregate as well?

This change does not break the build for the library target so if not I think it would still be worth merging.

It may also be worth updating the framework committed to the repo so that clients can use that

https://github.com/NeoSmartpen/IOS-SDK2.0/tree/master/iOSSDK2.0_sample_code/NISDK.framework

Or better yet, making this available as a cocoapod

https://github.com/NeoSmartpen/IOS-SDK2.0/issues/13

**Comment by mustafardestroyer** [comment]
Also, it seems that to actually obtain a copy of the Framework for use in your application you need to use the Framework build as it saves it to desktop per the script.

I'd be happy to add this info to the readme and open another PR updating the framework committed to the example code if you guys are interested!

**Comment by Jin-neo** [comment]
I checked your commit.

**Pull request merged**
